language: node_js
node_js:
- 'stable'
script:
- npm test -- --coverage
env:
  global:
    secure: GrRduj+gIrQzGqme5nWw1mTBD5YjZrHdaDmiJW1mOgJzt+iapenfqH1n7HRu31FV1P9ikIj84V2OSXqRhYhpOJJmBdqKASmqSq8rLVXpIif8KKpxzagu6wl9umFl094AiNL+vAvuipvJoInKo1IH8iipATd18Lsvdr8BY05S9Fw=
